export const ERROR_CODES = {
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    BAD_REQUEST: 'BAD_REQUEST',
    REQUEST_DID_NOT_MATCH: 'REQUEST_DID_NOT_MATCH',
    UNAUTHORIZED: 'UNAUTHORIZED',
    INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
    NOT_FOUND: 'NOT_FOUND',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    GONE: 'GONE',
    NOT_ACCEPTABLE: 'NOT_ACCEPTABLE',

};
